version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mongodb

  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

volumes:
  data:
  logs:
